package provider

import (
	"context"

	"github.com/algolia/algoliasearch-client-go/v4/algolia/search"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/ECCOShoes/terraform-provider-algolia/internal/client"
)

var (
	_ resource.Resource                = (*apiKeyResource)(nil)
	_ resource.ResourceWithConfigure   = (*apiKeyResource)(nil)
	_ resource.ResourceWithImportState = (*apiKeyResource)(nil)
)

type apiKeyResource struct {
	client *search.APIClient
}

type apiKeyModel struct {
	ID                     types.String `tfsdk:"id"`
	Key                    types.String `tfsdk:"key"`
	ACL                    types.List   `tfsdk:"acl"`
	Description            types.String `tfsdk:"description"`
	Indexes                types.List   `tfsdk:"indexes"`
	MaxHitsPerQuery        types.Int64  `tfsdk:"max_hits_per_query"`
	MaxQueriesPerIPPerHour types.Int64  `tfsdk:"max_queries_per_ip_per_hour"`
	QueryParameters        types.String `tfsdk:"query_parameters"`
	Referers               types.List   `tfsdk:"referers"`
	Validity               types.Int64  `tfsdk:"validity"`
	CreatedAt              types.Int64  `tfsdk:"created_at"`
}

// NewAPIKeyResource constructs the api_key resource.
func NewAPIKeyResource() resource.Resource {
	return &apiKeyResource{}
}

func (r *apiKeyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_api_key"
}

func (r *apiKeyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages an Algolia API key. The key value is generated by Algolia and is used as the resource ID.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				Description:   "The generated API key value, used as the resource identifier.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"key": schema.StringAttribute{
				Computed:      true,
				Sensitive:     true,
				Description:   "The generated API key value.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"acl": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    true,
				Description: "Permissions (access control list) that determine the type of API requests this key can make, e.g. search, browse, addObject, editSettings.",
			},
			"description": schema.StringAttribute{
				Optional:    true,
				Description: "Description to help identify the API key.",
			},
			"indexes": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Description: "Index names or patterns this API key can access. Supports leading and trailing wildcards (*).",
			},
			"max_hits_per_query": schema.Int64Attribute{
				Optional:    true,
				Description: "Maximum number of results this API key can retrieve in one query.",
			},
			"max_queries_per_ip_per_hour": schema.Int64Attribute{
				Optional:    true,
				Description: "Maximum number of API requests allowed per IP address per hour.",
			},
			"query_parameters": schema.StringAttribute{
				Optional:    true,
				Description: "Query parameters to add when making API requests with this API key.",
			},
			"referers": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Description: "Allowed HTTP referrers for this API key. Supports leading and trailing wildcards (*).",
			},
			"validity": schema.Int64Attribute{
				Optional:      true,
				Description:   "Duration in seconds after which the API key expires. By default, API keys don't expire. Changing this forces a new key.",
				PlanModifiers: []planmodifier.Int64{int64planmodifier.RequiresReplace()},
			},
			"created_at": schema.Int64Attribute{
				Computed:    true,
				Description: "Timestamp when the key was created, in milliseconds since the Unix epoch.",
			},
		},
	}
}

func (r *apiKeyResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromProviderData(req.ProviderData, &resp.Diagnostics)
}

func (r *apiKeyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan apiKeyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiKey, diags := r.expandAPIKey(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	created, err := r.client.AddApiKey(r.client.NewApiAddApiKeyRequest(apiKey))
	if err != nil {
		resp.Diagnostics.AddError("Unable to create API key", err.Error())
		return
	}

	// Wait until the key is readable, then use the returned details to populate
	// computed fields (creation is eventually consistent across Algolia's
	// servers).
	got, err := r.client.WaitForApiKey(created.Key, search.API_KEY_OPERATION_ADD)
	if err != nil {
		resp.Diagnostics.AddError("Unable to confirm API key creation", err.Error())
		return
	}

	plan.ID = types.StringValue(created.Key)
	plan.Key = types.StringValue(created.Key)
	if got != nil {
		plan.CreatedAt = types.Int64Value(got.CreatedAt)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *apiKeyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state apiKeyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	key := state.ID.ValueString()
	got, err := r.client.GetApiKey(r.client.NewApiGetApiKeyRequest(key))
	if err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read API key", err.Error())
		return
	}

	state.ID = types.StringValue(key)
	state.Key = types.StringValue(key)
	state.ACL = flattenStringList(aclToStrings(got.Acl))
	state.Description = stringValue(got.Description)
	state.Indexes = flattenStringList(got.Indexes)
	state.MaxHitsPerQuery = int64Value(got.MaxHitsPerQuery)
	state.MaxQueriesPerIPPerHour = int64Value(got.MaxQueriesPerIPPerHour)
	state.QueryParameters = stringValue(got.QueryParameters)
	state.Referers = flattenStringList(got.Referers)
	state.Validity = int64Value(got.Validity)
	state.CreatedAt = types.Int64Value(got.CreatedAt)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *apiKeyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state apiKeyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiKey, diags := r.expandAPIKey(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	key := state.ID.ValueString()
	if _, err := r.client.UpdateApiKey(r.client.NewApiUpdateApiKeyRequest(key, apiKey)); err != nil {
		resp.Diagnostics.AddError("Unable to update API key", err.Error())
		return
	}
	if _, err := r.client.WaitForApiKey(key, search.API_KEY_OPERATION_UPDATE, search.WithApiKey(apiKey)); err != nil {
		resp.Diagnostics.AddError("Unable to confirm API key update", err.Error())
		return
	}

	plan.ID = state.ID
	plan.Key = state.Key
	plan.CreatedAt = state.CreatedAt
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *apiKeyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state apiKeyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	key := state.ID.ValueString()
	if _, err := r.client.DeleteApiKey(r.client.NewApiDeleteApiKeyRequest(key)); err != nil && !client.IsNotFound(err) {
		resp.Diagnostics.AddError("Unable to delete API key", err.Error())
		return
	}
	if _, err := r.client.WaitForApiKey(key, search.API_KEY_OPERATION_DELETE); err != nil {
		resp.Diagnostics.AddError("Unable to confirm API key deletion", err.Error())
	}
}

func (r *apiKeyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func (r *apiKeyResource) expandAPIKey(ctx context.Context, model apiKeyModel) (*search.ApiKey, diag.Diagnostics) {
	var diags diag.Diagnostics

	acl, d := expandStringList(ctx, model.ACL)
	diags.Append(d...)
	indexes, d := expandStringList(ctx, model.Indexes)
	diags.Append(d...)
	referers, d := expandStringList(ctx, model.Referers)
	diags.Append(d...)
	if diags.HasError() {
		return nil, diags
	}

	apiKey := &search.ApiKey{
		Acl:                    stringsToACL(acl),
		Description:            stringPtr(model.Description),
		Indexes:                indexes,
		MaxHitsPerQuery:        int32Ptr(model.MaxHitsPerQuery),
		MaxQueriesPerIPPerHour: int32Ptr(model.MaxQueriesPerIPPerHour),
		QueryParameters:        stringPtr(model.QueryParameters),
		Referers:               referers,
		Validity:               int32Ptr(model.Validity),
	}
	return apiKey, diags
}

func stringsToACL(values []string) []search.Acl {
	acls := make([]search.Acl, 0, len(values))
	for _, v := range values {
		acls = append(acls, search.Acl(v))
	}
	return acls
}

func aclToStrings(acls []search.Acl) []string {
	if acls == nil {
		return nil
	}
	values := make([]string, 0, len(acls))
	for _, a := range acls {
		values = append(values, string(a))
	}
	return values
}
